"""
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
"""


def fib(n):
    if n <= 2:
        return n
    return fib(n - 1) + fib(n - 2)


lim = 4*10**6
s = 0

i = 1
fib_val = 1

while fib_val < lim:
    fib_val = fib(i)
    if fib_val % 2 == 0:
        s += fib_val
    i += 1

print(s)